"""Add Property and List models for PropertyRadar imports

Revision ID: 66c5792ba0da
Revises: 7ae240d16d07
Create Date: 2025-09-01 02:20:26.923893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c5792ba0da'
down_revision: Union[str, Sequence[str], None] = '7ae240d16d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'PROCESSING', 'COMPLETED', 'FAILED', 'ARCHIVED', name='liststatus'), nullable=False),
    sa.Column('source', sa.Enum('PROPERTY_RADAR', 'MANUAL_UPLOAD', 'API_IMPORT', 'OTHER', name='listsource'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('total_rows_imported', sa.Integer(), nullable=False),
    sa.Column('properties_created', sa.Integer(), nullable=False),
    sa.Column('properties_updated', sa.Integer(), nullable=False),
    sa.Column('contacts_created', sa.Integer(), nullable=False),
    sa.Column('contacts_updated', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('import_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('import_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('sample_data', sa.Text(), nullable=True),
    sa.Column('primary_city', sa.String(length=100), nullable=True),
    sa.Column('primary_state', sa.String(length=2), nullable=True),
    sa.Column('zip_codes_covered', sa.Text(), nullable=True),
    sa.Column('min_property_value', sa.Integer(), nullable=True),
    sa.Column('max_property_value', sa.Integer(), nullable=True),
    sa.Column('avg_property_value', sa.Integer(), nullable=True),
    sa.Column('high_equity_count', sa.Integer(), nullable=False),
    sa.Column('avg_equity_percent', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lists_created_at'), 'lists', ['created_at'], unique=False)
    op.create_index(op.f('ix_lists_id'), 'lists', ['id'], unique=False)
    op.create_index(op.f('ix_lists_import_started_at'), 'lists', ['import_started_at'], unique=False)
    op.create_index(op.f('ix_lists_name'), 'lists', ['name'], unique=False)
    op.create_index(op.f('ix_lists_primary_city'), 'lists', ['primary_city'], unique=False)
    op.create_index(op.f('ix_lists_source'), 'lists', ['source'], unique=False)
    op.create_index(op.f('ix_lists_status'), 'lists', ['status'], unique=False)
    op.create_index(op.f('ix_lists_total_rows_imported'), 'lists', ['total_rows_imported'], unique=False)
    op.create_index(op.f('ix_lists_user_id'), 'lists', ['user_id'], unique=False)
    op.create_table('properties',
    sa.Column('property_type', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('subdivision', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('apn', sa.String(length=50), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_months_since', sa.Integer(), nullable=True),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('est_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('est_equity_dollar', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('est_equity_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('high_equity', sa.Boolean(), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('mail_address', sa.String(length=200), nullable=True),
    sa.Column('mail_city', sa.String(length=100), nullable=True),
    sa.Column('mail_state', sa.String(length=2), nullable=True),
    sa.Column('mail_zip', sa.String(length=10), nullable=True),
    sa.Column('owner_occupied', sa.Boolean(), nullable=True),
    sa.Column('listed_for_sale', sa.Boolean(), nullable=True),
    sa.Column('listing_status', sa.String(length=50), nullable=True),
    sa.Column('foreclosure', sa.Boolean(), nullable=True),
    sa.Column('source_list_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_list_id'], ['lists.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address', 'city', 'zip_code', name='uq_properties_address_city_zip')
    )
    op.create_index(op.f('ix_properties_address'), 'properties', ['address'], unique=False)
    op.create_index(op.f('ix_properties_apn'), 'properties', ['apn'], unique=True)
    op.create_index(op.f('ix_properties_bathrooms'), 'properties', ['bathrooms'], unique=False)
    op.create_index(op.f('ix_properties_bedrooms'), 'properties', ['bedrooms'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index('ix_properties_city_zip', 'properties', ['city', 'zip_code'], unique=False)
    op.create_index(op.f('ix_properties_created_at'), 'properties', ['created_at'], unique=False)
    op.create_index('ix_properties_equity_value', 'properties', ['est_equity_percent', 'est_value'], unique=False)
    op.create_index(op.f('ix_properties_est_equity_dollar'), 'properties', ['est_equity_dollar'], unique=False)
    op.create_index(op.f('ix_properties_est_equity_percent'), 'properties', ['est_equity_percent'], unique=False)
    op.create_index(op.f('ix_properties_est_value'), 'properties', ['est_value'], unique=False)
    op.create_index('ix_properties_for_sale', 'properties', ['listed_for_sale'], unique=False)
    op.create_index(op.f('ix_properties_foreclosure'), 'properties', ['foreclosure'], unique=False)
    op.create_index('ix_properties_high_equity', 'properties', ['high_equity'], unique=False)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index('ix_properties_lat_lng', 'properties', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_properties_listed_for_sale'), 'properties', ['listed_for_sale'], unique=False)
    op.create_index(op.f('ix_properties_owner_name'), 'properties', ['owner_name'], unique=False)
    op.create_index('ix_properties_owner_occupied', 'properties', ['owner_occupied'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_purchase_date'), 'properties', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_properties_purchase_months_since'), 'properties', ['purchase_months_since'], unique=False)
    op.create_index(op.f('ix_properties_source_list_id'), 'properties', ['source_list_id'], unique=False)
    op.create_index(op.f('ix_properties_square_feet'), 'properties', ['square_feet'], unique=False)
    op.create_index(op.f('ix_properties_subdivision'), 'properties', ['subdivision'], unique=False)
    op.create_index(op.f('ix_properties_year_built'), 'properties', ['year_built'], unique=False)
    op.create_index(op.f('ix_properties_zip_code'), 'properties', ['zip_code'], unique=False)
    op.create_table('contact_property_relationships',
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.Column('source_list_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_list_id'], ['lists.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('contact_id', 'property_id')
    )
    op.create_index('ix_contact_property_contact_id', 'contact_property_relationships', ['contact_id'], unique=False)
    op.create_index('ix_contact_property_list_id', 'contact_property_relationships', ['source_list_id'], unique=False)
    op.create_index('ix_contact_property_property_id', 'contact_property_relationships', ['property_id'], unique=False)
    op.add_column('campaigns', sa.Column('source_list_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_campaigns_source_list_id'), 'campaigns', ['source_list_id'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'lists', ['source_list_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index(op.f('ix_campaigns_source_list_id'), table_name='campaigns')
    op.drop_column('campaigns', 'source_list_id')
    op.drop_index('ix_contact_property_property_id', table_name='contact_property_relationships')
    op.drop_index('ix_contact_property_list_id', table_name='contact_property_relationships')
    op.drop_index('ix_contact_property_contact_id', table_name='contact_property_relationships')
    op.drop_table('contact_property_relationships')
    op.drop_index(op.f('ix_properties_zip_code'), table_name='properties')
    op.drop_index(op.f('ix_properties_year_built'), table_name='properties')
    op.drop_index(op.f('ix_properties_subdivision'), table_name='properties')
    op.drop_index(op.f('ix_properties_square_feet'), table_name='properties')
    op.drop_index(op.f('ix_properties_source_list_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_purchase_months_since'), table_name='properties')
    op.drop_index(op.f('ix_properties_purchase_date'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index('ix_properties_owner_occupied', table_name='properties')
    op.drop_index(op.f('ix_properties_owner_name'), table_name='properties')
    op.drop_index(op.f('ix_properties_listed_for_sale'), table_name='properties')
    op.drop_index('ix_properties_lat_lng', table_name='properties')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index('ix_properties_high_equity', table_name='properties')
    op.drop_index(op.f('ix_properties_foreclosure'), table_name='properties')
    op.drop_index('ix_properties_for_sale', table_name='properties')
    op.drop_index(op.f('ix_properties_est_value'), table_name='properties')
    op.drop_index(op.f('ix_properties_est_equity_percent'), table_name='properties')
    op.drop_index(op.f('ix_properties_est_equity_dollar'), table_name='properties')
    op.drop_index('ix_properties_equity_value', table_name='properties')
    op.drop_index(op.f('ix_properties_created_at'), table_name='properties')
    op.drop_index('ix_properties_city_zip', table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_bedrooms'), table_name='properties')
    op.drop_index(op.f('ix_properties_bathrooms'), table_name='properties')
    op.drop_index(op.f('ix_properties_apn'), table_name='properties')
    op.drop_index(op.f('ix_properties_address'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_lists_user_id'), table_name='lists')
    op.drop_index(op.f('ix_lists_total_rows_imported'), table_name='lists')
    op.drop_index(op.f('ix_lists_status'), table_name='lists')
    op.drop_index(op.f('ix_lists_source'), table_name='lists')
    op.drop_index(op.f('ix_lists_primary_city'), table_name='lists')
    op.drop_index(op.f('ix_lists_name'), table_name='lists')
    op.drop_index(op.f('ix_lists_import_started_at'), table_name='lists')
    op.drop_index(op.f('ix_lists_id'), table_name='lists')
    op.drop_index(op.f('ix_lists_created_at'), table_name='lists')
    op.drop_table('lists')
    # ### end Alembic commands ###
