"""Add A/B testing fields to campaigns

Revision ID: 7ae240d16d07
Revises: 8297d65a3222
Create Date: 2025-08-31 20:09:05.528537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae240d16d07'
down_revision: Union[str, Sequence[str], None] = '8297d65a3222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('message_template_b', sa.Text(), nullable=True))
    op.add_column('campaigns', sa.Column('ab_test_percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'ab_test_percentage')
    op.drop_column('campaigns', 'message_template_b')
    # ### end Alembic commands ###
