"""Update schema to match current models

Revision ID: 92bfaf4ecd7d
Revises: 001
Create Date: 2025-08-31 19:05:21.856138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92bfaf4ecd7d'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    op.add_column('messages', sa.Column('external_id', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='messagedirection'), nullable=False))
    op.add_column('messages', sa.Column('message_type', sa.Enum('SMS', 'CALL', 'VOICEMAIL', name='messagetype'), nullable=False))
    op.add_column('messages', sa.Column('from_phone', sa.String(length=20), nullable=True))
    op.add_column('messages', sa.Column('to_phone', sa.String(length=20), nullable=True))
    op.add_column('messages', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('received_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('messages', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_direction'), 'messages', ['direction'], unique=False)
    op.create_index(op.f('ix_messages_external_id'), 'messages', ['external_id'], unique=True)
    op.create_index(op.f('ix_messages_from_phone'), 'messages', ['from_phone'], unique=False)
    op.create_index(op.f('ix_messages_message_type'), 'messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_messages_received_at'), 'messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_messages_to_phone'), 'messages', ['to_phone'], unique=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('webhook_events', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('webhook_events', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.create_index(op.f('ix_webhook_events_created_at'), 'webhook_events', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_created_at'), table_name='webhook_events')
    op.alter_column('webhook_events', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('webhook_events', 'updated_at')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_messages_to_phone'), table_name='messages')
    op.drop_index(op.f('ix_messages_received_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_from_phone'), table_name='messages')
    op.drop_index(op.f('ix_messages_external_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_direction'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.alter_column('messages', 'campaign_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'updated_at')
    op.drop_column('messages', 'received_at')
    op.drop_column('messages', 'duration_seconds')
    op.drop_column('messages', 'to_phone')
    op.drop_column('messages', 'from_phone')
    op.drop_column('messages', 'message_type')
    op.drop_column('messages', 'direction')
    op.drop_column('messages', 'body')
    op.drop_column('messages', 'external_id')
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_table_pkey')
    )
    # ### end Alembic commands ###
